/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  FramekitHighlightCodeAnchor,
} from './components/declarations/fk-highlight-code-anchor';


export namespace Components {

  interface BpdsAccordion {
    'accordionContainerHeight': any;
    'convToHTMLElement': any;
    'cssClass'?: string;
    'currentTab': () => Promise<number>;
    'expand': (accordionPanelIndex: number) => void;
    'getNewHeight': () => Promise<string>;
    'height'?: string;
    'idx': any;
    'openAccordionPanel': (accordionPanelIndex: number) => void;
    'removeFocus': (accordionPanelIndex: number) => void;
    'value': string;
    'width'?: string;
  }
  interface BpdsAccordionAttributes extends StencilHTMLAttributes {
    'accordionContainerHeight'?: any;
    'convToHTMLElement'?: any;
    'cssClass'?: string;
    'height'?: string;
    'idx'?: any;
    'onChange'?: (event: CustomEvent) => void;
    'value'?: string;
    'width'?: string;
  }

  interface BpdsAccordionPanel {
    'disabled': boolean;
    'header': string;
    'open': boolean;
    'type': string;
  }
  interface BpdsAccordionPanelAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'header'?: string;
    'open'?: boolean;
    'type'?: string;
  }

  interface FkHighlightCode {
    'anchor': string;
    'anchorZoom': string;
    'findNextAnchor': (enter: boolean) => Promise<FramekitHighlightCodeAnchor>;
    'hideAnchor': boolean;
    'highlightLines': string;
    'language': string;
    'load': () => Promise<void>;
    'src': string;
    'zoomCode': (zoom: boolean) => Promise<void>;
  }
  interface FkHighlightCodeAttributes extends StencilHTMLAttributes {
    'anchor'?: string;
    'anchorZoom'?: string;
    'hideAnchor'?: boolean;
    'highlightLines'?: string;
    'language'?: string;
    'onPrismLanguageLoaded'?: (event: CustomEvent<string>) => void;
    'src'?: string;
  }

  interface FkTab {
    'disabled': boolean;
    'header': string;
    'open': boolean;
    'type': string;
  }
  interface FkTabAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'header'?: string;
    'open'?: boolean;
    'type'?: string;
  }

  interface FkTabs {
    'convToHTMLElement': any;
    'cssClass'?: string;
    'currentTab': () => Promise<number>;
    'expand': (tabIndex: number) => void;
    'getNewHeight': () => Promise<string>;
    'height'?: string;
    'idx': any;
    'openTab': (tabIndex: number) => void;
    'removeFocus': (tabIndex: number) => void;
    'tabContainerHeight': any;
    'value': string;
    'width'?: string;
  }
  interface FkTabsAttributes extends StencilHTMLAttributes {
    'convToHTMLElement'?: any;
    'cssClass'?: string;
    'height'?: string;
    'idx'?: any;
    'onChange'?: (event: CustomEvent) => void;
    'tabContainerHeight'?: any;
    'value'?: string;
    'width'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BpdsAccordion': Components.BpdsAccordion;
    'BpdsAccordionPanel': Components.BpdsAccordionPanel;
    'FkHighlightCode': Components.FkHighlightCode;
    'FkTab': Components.FkTab;
    'FkTabs': Components.FkTabs;
  }

  interface StencilIntrinsicElements {
    'bpds-accordion': Components.BpdsAccordionAttributes;
    'bpds-accordion-panel': Components.BpdsAccordionPanelAttributes;
    'fk-highlight-code': Components.FkHighlightCodeAttributes;
    'fk-tab': Components.FkTabAttributes;
    'fk-tabs': Components.FkTabsAttributes;
  }


  interface HTMLBpdsAccordionElement extends Components.BpdsAccordion, HTMLStencilElement {}
  var HTMLBpdsAccordionElement: {
    prototype: HTMLBpdsAccordionElement;
    new (): HTMLBpdsAccordionElement;
  };

  interface HTMLBpdsAccordionPanelElement extends Components.BpdsAccordionPanel, HTMLStencilElement {}
  var HTMLBpdsAccordionPanelElement: {
    prototype: HTMLBpdsAccordionPanelElement;
    new (): HTMLBpdsAccordionPanelElement;
  };

  interface HTMLFkHighlightCodeElement extends Components.FkHighlightCode, HTMLStencilElement {}
  var HTMLFkHighlightCodeElement: {
    prototype: HTMLFkHighlightCodeElement;
    new (): HTMLFkHighlightCodeElement;
  };

  interface HTMLFkTabElement extends Components.FkTab, HTMLStencilElement {}
  var HTMLFkTabElement: {
    prototype: HTMLFkTabElement;
    new (): HTMLFkTabElement;
  };

  interface HTMLFkTabsElement extends Components.FkTabs, HTMLStencilElement {}
  var HTMLFkTabsElement: {
    prototype: HTMLFkTabsElement;
    new (): HTMLFkTabsElement;
  };

  interface HTMLElementTagNameMap {
    'bpds-accordion': HTMLBpdsAccordionElement
    'bpds-accordion-panel': HTMLBpdsAccordionPanelElement
    'fk-highlight-code': HTMLFkHighlightCodeElement
    'fk-tab': HTMLFkTabElement
    'fk-tabs': HTMLFkTabsElement
  }

  interface ElementTagNameMap {
    'bpds-accordion': HTMLBpdsAccordionElement;
    'bpds-accordion-panel': HTMLBpdsAccordionPanelElement;
    'fk-highlight-code': HTMLFkHighlightCodeElement;
    'fk-tab': HTMLFkTabElement;
    'fk-tabs': HTMLFkTabsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
